name: OpsyUnEnchanter
version: 1.0
author: ZeTioZ
main: fr.opsycraft.unenchanter.Main
commands:
  desenchant:
    aliases: [desench, ds]
    description: Main desenchanter command
  desenchant give:
    description: Drop you a special anvil and an unlock-scroll
    permission: opsyunenchanter.give
  desenchant help:
    description: Plugin help command
  desenchant reload:
    description: Reload the plugin
    permission: opsyunenchanter.reload
  permissions:
    opsyunenchanter.use: Allow players to place a special anvil
    opsyunenchanter.place: Allow players to place a special anvil
    opsyunenchanter.break: Allow players to break special anvil
